# Generated by Django 6.0.7 on 2026-07-18 05:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_id', models.CharField(blank=True, max_length=200, null=True, unique=True)),
                ('name', models.CharField(max_length=1024, unique=True)),
                ('exchange_ticker', models.CharField(blank=True, max_length=200, null=True)),
                ('primary_sector', models.CharField(blank=True, max_length=256, null=True)),
                ('primary_industry', models.CharField(blank=True, max_length=256, null=True)),
                ('headquarters_country_region', models.CharField(blank=True, max_length=256, null=True)),
                ('website', models.CharField(blank=True, max_length=512, null=True)),
                ('business_description', models.TextField(blank=True, null=True)),
                ('industry_classifications', models.CharField(blank=True, max_length=1024, null=True)),
                ('country', models.CharField(blank=True, max_length=256, null=True)),
                ('first_pricing_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectDates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gpc_date', models.CharField(blank=True, max_length=100, null=True)),
                ('transaction_date', models.CharField(blank=True, max_length=100, null=True)),
                ('audit_date', models.CharField(blank=True, max_length=100, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='UploadJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('filename', models.CharField(blank=True, max_length=255)),
                ('summary', models.JSONField(default=dict)),
                ('file', models.FileField(blank=True, null=True, upload_to='uploads/finance/')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FinancialRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(default='latest', max_length=50)),
                ('market_cap', models.DecimalField(blank=True, decimal_places=6, max_digits=30, null=True)),
                ('total_revenue', models.DecimalField(blank=True, decimal_places=6, max_digits=30, null=True)),
                ('enterprise_value', models.DecimalField(blank=True, decimal_places=6, max_digits=30, null=True)),
                ('ebitda', models.DecimalField(blank=True, decimal_places=6, max_digits=30, null=True)),
                ('ev_revenu', models.DecimalField(blank=True, decimal_places=6, max_digits=30, null=True)),
                ('ev_ebitda', models.DecimalField(blank=True, decimal_places=6, max_digits=30, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='buyerslist.company')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('company', 'period')},
            },
        ),
    ]
